services:
  - type: web
    name: eld-trip-planner-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi --timeout 60 --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
